server:
  forward-headers-strategy: none
  port: 8080
  servlet:
    context-path: /modulith-demo
hostname: localdev

config:
  server:
    url: http://localhost:${server.port}

  datasource:
    server: localhost:5432
    ssl: false
    sslmode: disable
    database: modulith
    username: dev
    password: pwd

  keycloak:
    server: http://localhost:8180
    realm: modulith
    client: modulith
    secret: xOWbdLzfyqgxrg9w2TPx2NvNr8oN5464

spring:
  application:
    name: modulith

  docker:
    compose:
      file: 'docker/docker-compose.yaml'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${config.keycloak.server}/realms/${config.keycloak.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${config.keycloak.server}/realms/${config.keycloak.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: ${config.keycloak.client}
            client-secret: ${config.keycloak.secret}
            authorization-grant-type: client_credentials
  jpa:
    show-sql: false
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://${config.datasource.server}/${config.datasource.database}?&ApplicationName=${hostname}&ssl=${config.datasource.ssl}&sslmode=${config.datasource.sslmode}
    #    username: ${config.datasource.username}
    #    password: ${config.datasource.password}
    hikari:
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      idle-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 4
      connection-timeout: 20000
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    liquibase-schema: migration
  management:
    tracing.sampling.probability: 1.0
    endpoints:
      web:
        base-path: "/actuator"
        exposure:
          include: prometheus, health
    endpoint:
      health:
        probe:
          enabled: true
    server:
      port: 8081
springdoc:
  packagesToScan: com.example
  swagger-ui:
    deep-linking: true
    doc-expansion: none

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{username:-}]"
logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
