version: "3.9"
services:
  postgres:
    container_name: postgres_modulith
    image: "postgres:latest"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - env/database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin_modulith
    image: "dpage/pgadmin4:latest"
    env_file:
      - env/database.dev.env
    volumes:
      - ./init/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - backend
  keycloak:
    container_name: keycloak_modulith
    image: "quay.io/keycloak/keycloak:latest"
    command: start-dev --import-realm
    depends_on:
      - elastic
      - kibana
    env_file:
      - env/keycloak.dev.env
    volumes:
      - ./init/keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend
  elastic:
    container_name: elastic_modulith
    image: "elasticsearch:8.7.1"
    env_file:
      - env/es.dev.env
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend
  kibana:
    container_name: kibana_modulith
    image: "kibana:8.7.1"
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    env_file:
      - env/kibana.dev.env
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
